[package]
name = "tonguetoquill-classic"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Nibs"]
license = "MIT"
description = "A classic resume template based on the Carnegie Classic specifications."

categories = ["office"]

[template]
path = "template/classic-resume.typ"
entrypoint = "template/classic-resume.typ"
thumbnail = "thumbnail.png"
